workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_WORKSPACE: "BubblyBass.xcworkspace"
        XCODE_SCHEME: "BubblyBass"
        BUNDLE_ID: "com.ott.bubbl7b4s"
        EXTENSION_BUNDLE_ID: "com.ott.bubbl7b4s.OneSignalNotificationServiceExtension"
      xcode: latest
      cocoapods: default  # Используйте default вместо фиксированной версии

    scripts:
      - name: Set up keychain
        script: |
          keychain initialize

      - name: Fetch signing files for both targets
        script: |
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            "$EXTENSION_BUNDLE_ID" \
            --type IOS_APP_STORE \
            --platform IOS \
            --create

      - name: Add certificates to keychain
        script: |
          keychain add-certificates

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Install CocoaPods
        script: |
          pod install

      - name: Build IPA for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --output "build/ios/ipa"

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
